# Generated by Django 4.1.2 on 2022-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
