# Generated by Django 4.1.2 on 2022-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment_parent_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='head_comment',
            field=models.BooleanField(default=False),
        ),
    ]
