# Generated by Django 4.1.2 on 2022-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment_head_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='head_comment',
            field=models.BooleanField(default=True),
        ),
    ]
