# Generated by Django 4.1.2 on 2022-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='модератор'),
        ),
    ]
