# Generated by Django 3.1.7 on 2022-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20221009_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='about_me',
            field=models.TextField(blank=True, max_length=512, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='BlogUserProfile',
        ),
    ]
