# Generated by Django 4.1.2 on 2022-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_bloguser_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='banned_time',
            field=models.IntegerField(default=0, verbose_name='Период блокировки'),
        ),
    ]
