# Generated by Django 4.1.2 on 2022-10-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_auto_20221009_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
