# Generated by Django 4.1.2 on 2022-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_bloguser_banned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='stop_banned_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания блокировки'),
        ),
    ]
