# Generated by Django 3.1.7 on 2022-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_bloguser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='banned_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период блокировки'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='start_banned_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала блокировки'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
